services:
  # ============================================
  # SQL Server Database
  # ============================================
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: adres-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD:-YourStrong@Passw0rd}
      MSSQL_PID: ${MSSQL_PID:-Developer}
      SA_PASSWORD: ${SA_PASSWORD:-YourStrong@Passw0rd}
    ports:
      - "${SQL_SERVER_PORT:-1433}:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    # Healthcheck deshabilitado temporalmente para servidores Linux
    # Si SQL Server inicia correctamente, el healthcheck no es crítico
    # healthcheck:
    #   test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrong@Passw0rd' -Q 'SELECT 1' -b -o /dev/null"]
    #   interval: 15s
    #   timeout: 10s
    #   retries: 10
    #   start_period: 90s
    networks:
      - adres-network
    restart: unless-stopped

  # ============================================
  # Backend API - ASP.NET Core 8
  # ============================================
  api:
    build:
      context: ./adres.api
      dockerfile: Dockerfile
    container_name: adres-api
    env_file:
      - ./adres.api/.env
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=${DB_NAME:-AdresDb};User ID=${DB_USER:-sa};Password=${SA_PASSWORD:-YourStrong@Passw0rd};TrustServerCertificate=True;Encrypt=False"
    ports:
      - "${API_PORT:-8080}:8080"
    depends_on:
      - sqlserver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - adres-network
    restart: unless-stopped

  # ============================================
  # Frontend - React + Nginx
  # ============================================
  web:
    build:
      context: ./adres-web
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL:-http://localhost:8080/api}
    container_name: adres-web
    env_file:
      - ./adres-web/.env
    ports:
      - "${WEB_PORT:-3000}:80"
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - adres-network
    restart: unless-stopped

volumes:
  sqlserver_data:
    driver: local

networks:
  adres-network:
    driver: bridge
